@Controllers_HostAddress = http://localhost:5099

# GET {{Controllers_HostAddress}}/api/books
# Accept: application/json


# POST {{Controllers_HostAddress}}/api/books
# Accept: application/json
# Content-Type: application/json

# {
#   "title": "Clean Code",
#   "author": "Robert Martin",
#   "year": 2008
# }


# PUT {{Controllers_HostAddress}}/api/books/2
# Accept: application/json
# Content-Type: application/json

# {
#   "title": "Clean Code - Updated",
#   "author": "Robert Martin",
#   "year": 2026
# }

# DELETE {{Controllers_HostAddress}}/api/books/2
# Accept: application/json

# POST {{Controllers_HostAddress}}/api/books
# Content-Type: application/json
# x-user-role: user

# {
#   "title": "Brave New World",
#   "author": "Aldous Huxley",
#   "year": 1932
# }

# POST {{Controllers_HostAddress}}/api/books
# Content-Type: application/json
# x-user-role: admin

# {
#   "title": "Brave New World",
#   "author": "Aldous Huxley",
#   "year": 1932
# }

GET {{Controllers_HostAddress}}/api/books/4
Accept: application/json